controllers:
    resource:
        path: ../src/Controller/
        namespace: adamcameron\php8\Controller
    type: attribute

PostcodeLookup:
    path: /postcode-lookup/{postcode}
    controller: adamcameron\php8\Controller\PostcodeLookupController::doGet
    methods: GET

Observer:
    path: /observer/{message}
    controller: adamcameron\php8\designpatterns\observer\Controller::doGet
    methods: GET
